### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by Bengt** [HELMpy/HELMpy#10]
The current setup of reading and writing files works okay for experiments. These experiments could already be used as tests with decent coverage in #8. However the file-based API is clearly not meant for reusing the code as a library in other projects. So provide a clear and simple API for reuse from Python functions/objects.

**Comment by Bengt** [comment]
I changed the API from using matlab case files to plain csv files reproducibility. These can be transformed into each other using exporting individual sheets to csv or importing them into one using excel. Therefore I did not bother automating this process, but that may be a desirable future feature.

**Comment by OrtegaJuanJose** [comment]
The csv were deleted because they contained errors. In the future matlab case files will stop being used as commented.
