### ISSUE TITLE
Integrate HELMpy in GridCal

### ISSUE THREAD

**Issue by SanPen** [HELMpy/HELMpy#3]
Hi!

I am the main developer of [GridCal](https://github.com/SanPen/GridCal).
It turns out that I published the first HELM code a couple of years ago, and I was never satisfied with the results I found...

Today I was directed to this repository by a colleague, and I wonder if you would like to consider the integration of your HELM implementation in GridCal. I would like to help as much as possible.

Thanks

**Comment by OrtegaJuanJose** [comment]
Hello Santiago,

I am truly sorry I never answered this message or any other. I did not followed up on this project, which a truly regret.

I want to start working on this project again and will like to help the community in the development of the HELM algorithm. I will like to contribute if you are still interested.

**Comment by SanPen** [comment]
Hi, 

Since I wrote there have been developments;

- Josep Fanals shared his code (see [here](https://github.com/u1946589/Holomorphic-Embedding-Josep))
- See the current implementation [here](https://github.com/SanPen/GridCal/blob/master/src/GridCal/Engine/Simulations/PowerFlow/helm_power_flow.py)

And currently we are working towards better implementations, [see this discussion](https://forum.openmod-initiative.org/t/the-new-helm-powerflow-in-gridcal/1952/17).

You are very welcome to join these efforts.

**Comment by HELMpy** [comment]
Thank you Santiago. I will go through the references.
